name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install awscli
      - run: npm ci
      - run: npm run build
      - name: Deploy
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # For some reason `aws s3` is always failing with error code 255 and this fixes it
          # https://github.com/actions/checkout/issues/440
          AWS_EC2_METADATA_DISABLED: true
        run: aws s3 sync _site s3://rwblickhan.org
