name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install awscli
      - run: git bundle create 11ty-rwblickhan.org.bundle --all
      - name: Backup
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # For some reason `aws s3` is always failing with error code 255 and this fixes it
          # https://github.com/actions/checkout/issues/440
          AWS_EC2_METADATA_DISABLED: true
        run: aws s3 cp 11ty-rwblickhan.org.bundle s3://rwblickhan.org-backup
