name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install awscli
      - name: Install Stork
        run: wget https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-20-04 && chmod +x stork-ubuntu-20-04
      - run: npm ci
      - run: npm run build
      - name: Build search index
        run: ./stork-ubuntu-20-04 build --input _site/stork-posts.toml --output _site/index.st
      - name: Publish index
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: r2 object put store-rwblickhanorg/index.st --file _site/index.st
      - name: Bundle
        run: git bundle create 11ty-rwblickhan.org.bundle --all
      - name: Backup
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # For some reason `aws s3` is always failing with error code 255 and this fixes it
          # https://github.com/actions/checkout/issues/440
          AWS_EC2_METADATA_DISABLED: true
        run: aws s3 cp 11ty-rwblickhan.org.bundle s3://rwblickhan.org-backup
